# Generated by Django 3.2.7 on 2021-09-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='manzil',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
