# Generated by Django 3.2.7 on 2021-09-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_manzil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='manzil',
            new_name='address',
        ),
    ]
